import { errors } from "./errors";
import obterCor from "./cores";
import {
  periodos,
  encontrarMinEMaxDatas,
  amdEmData,
  dataEmAmd,
  dataEmDm,
  dataEmDmahm,
  dataEmDma,
  filtraDatasPorIntervalo,
  obterDatasPorDiaSemana,
  todasAsDatasNoIntervalo,
  agruparDatasPorMes,
  obterPeriodoDoDia,
  comparaObjComDataInicial,
  diferencaAbsEmHoras,
  horarioEmData,
  separaDatasEmSemanas,
  DOMINGO,
  SEGUNDA,
  TERCA,
  QUARTA,
  QUINTA,
  SEXTA,
  SABADO,
  sortDatas,
} from "./datas";
import { gerarArquivoXLSX } from "./xlsx";
import { extenderArray, moverParaPrimeiraPosicao } from "./arrays";

export {
  errors,
  obterCor,
  periodos,
  encontrarMinEMaxDatas,
  amdEmData,
  dataEmAmd,
  dataEmDm,
  dataEmDmahm,
  dataEmDma,
  filtraDatasPorIntervalo,
  obterDatasPorDiaSemana,
  todasAsDatasNoIntervalo,
  agruparDatasPorMes,
  obterPeriodoDoDia,
  comparaObjComDataInicial,
  diferencaAbsEmHoras,
  horarioEmData,
  gerarArquivoXLSX,
  separaDatasEmSemanas,
  DOMINGO,
  SEGUNDA,
  TERCA,
  QUARTA,
  QUINTA,
  SEXTA,
  SABADO,
  sortDatas,
  extenderArray,
  moverParaPrimeiraPosicao,
};
